version: '3'
services:
  app:
    container_name: post-service
    build: .
    image: post-service:latest
    networks:
      - post-network
    ports:
      - "8080:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    restart: on-failure:5
networks:
  post-network:
  #for post service backend